name: deploy 

on:
  workflow_run:
    workflows: [test]
    branches: ["main"]
    types: [completed]

permissions:
  contents: read

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    
